image: registry.gitlab.com/oer/docker/emacs-reveal:1.0

pages:
  stage: deploy
  before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive
  script:
  - emacs --batch --load elisp/publish.el
  artifacts:
    paths:
    - public
    expire_in: 4 weeks
  only:
  - master
