image: registry.gitlab.com/oer/docker/debian-emacs-tex-org:v3.3

pages:
  stage: deploy
  script:
  - emacs --batch --load elisp/publish.el --funcall org-publish-all
  artifacts:
    paths:
    - public
    expire_in: 4 weeks
  only:
  - master
