#+INCLUDE: "preamble.org"

#+TITLE: Physical Layer 
#+AUTHOR: Mo, Yilin
#+DATE: Oct 2020 

#+KEYWORDS: physical layer
#+DESCRIPTION: physical layer for iot course

* Introduction
  
** Core Questions
   TODO
** Learning Objectives
   TODO
** Table of Contents
   :PROPERTIES:
   :UNNUMBERED: notoc
   :END:
#+REVEAL_TOC: headlines 1

* Overview

** OSI 7-Layer Network Model

    {{{revealimg("./figures/osimodel.meta",t,"60vh")}}}

** OSI Physical Layer
- The physical layer defines the means of transmitting raw bits over a physical data link connecting network nodes. 
- Deals with accessing the physical medium
  - Mechanical characteristics
  - Electrical characteristics
  - Functional characteristics
  - Procedural characteristics
    
** Wireless PHY protocols
  {{{revealimg("./figures/wirelesscommunication.meta","Various wireless communication protocols and categories designed for different ranges\, data rates\, and use cases","60vh",nil,'none)}}}
   
** Electromagnetic Spectrum
 
    {{{revealimg("./figures/emspectrum.meta",t,"60vh")}}}
 
** Radio Frequency (RF) Signal
 
    {{{revealimg("./figures/ituradioband.meta",t,"60vh")}}}
    
** RF Band Allocation

    {{{revealimg("./figures/usfreqallocation.meta",t,"60vh")}}}

- Frequency band is a very *rare* & *important* resource!
   
** ISM Band
  
- Radio spectrum reserved internationally for industrial, scientific and medical (ISM) purposes 
  - e.g., microwave ovens
- Fastest-growing use for low power wireless communications systems
  - e.g., WiFi, Bluetooth, Zigbee, LoRa
- Communications equipment must tolerate interference generated by ISM applications
| Frequency Range   | Center Frequency | Bandwidth | Availability |
| 433.05~434.79 MHz | 433.92 MHz       | 1.74 MHz  | Region 1     |
| 902~928 MHz       | 915 MHz          | 26 MHz    | Region 2     |
| 2.4~2.5 GHz       | 2.45 GHz         | 100 MHz   | Worldwide    |
| 5.725~5.875 GHz   | 5.8 GHz          | 150 MHz   | Worldwide    |

* Digital Modulation and Demodulation

** Modulation Overview
- Modulation is the process of varying one or more properties of a periodic waveform, called the *carrier signal*, with a *modulating signal* that typically contains information to be transmitted. 
- In digital modulation, an *analog carrier signal* is modulated by a *discrete signal*.
- The most fundamental digital modulation techniques are based on keying:
  - ASK (amplitude-shift keying): a finite number of amplitudes are used.
  - FSK (frequency-shift keying): a finite number of frequencies are used.
  - PSK (phase-shift keying): a finite number of phases are used.
  - QAM (quadrature amplitude modulation): a finite number of at least two phases and at least two amplitudes are used.

*** Rectangle Pulse and Sinc Function
#+BEGIN_SRC ipython :session :exports results :results output html :var filename="figures/rect.js"
from bokeh.resources import CDN
from bokeh.plotting import figure
from bokeh.embed import autoload_static
from bokeh.layouts import gridplot

from numpy import linspace, sinc

x = linspace(-5,5,200)
y = [1 if z <= 0.5 and z >= -0.5 else 0 for z in x]
p1 = figure(title = "Time Domain")
p1.line(x,y)

x = linspace(-20,20,400)  
y = sinc(x)
p2 = figure(title = "Frequence Domain")
p2.line(x,y)

p = gridplot([p1, p2], ncols = 2, plot_width = 600, plot_height = 600)


js, tag = autoload_static(p, CDN, filename)
f = open(filename, "w")
f.write(js)
f.close()

print(tag)
#+END_SRC

#+RESULTS:
#+begin_export html

<script src="figures/rect.js" id="9dadc6da-6030-4495-8ea9-3458a993e342"></script>
#+end_export

*** Power Spectral Density
    
#+BEGIN_SRC ipython :session :exports results :results output html :var filename="figures/psd.js"
from bokeh.resources import CDN
from bokeh.plotting import figure
from bokeh.embed import autoload_static
from bokeh.layouts import gridplot

from numpy import linspace, sinc

x = linspace(-20,20,400)  
y = sinc(x)
p = figure(title = "Power Spectral Density")
p.line(x,y**2)

js, tag = autoload_static(p, CDN, filename)
f = open(filename, "w")
f.write(js)
f.close()

print(tag)
#+END_SRC

#+RESULTS:
#+begin_export html

<script src="figures/psd.js" id="df3dc688-6fc5-4810-8ee3-6f8b2bdf4bbf"></script>
#+end_export

   
*** Fourier Transform (Revisit)
    
\[F(\omega ) = \int_{-\infty}^\infty f(t) \exp(2\pi i  \omega t)dt.\]
|                    | Time Domain                   | Frequency Domain                        |
| Linear Combination | \(a\times f(t)+b\times g(t)\) | \(a\times F(\omega)+b\times G(\omega)\) |
| Multiplication     | \( f(t)\times g(t)  \)        | \(F(\omega) * G(\omega)\)               |
| Delay              | \(f(t-\tau)\)                 |  \(\exp(-2\pi i \tau \omega) F(\omega)\) |

*** Fourier Transform

#+BEGIN_SRC ipython :session :exports results :results output html :var filename="figures/modulation.js"
from bokeh.resources import CDN
from bokeh.plotting import figure, show
from bokeh.embed import autoload_static
from bokeh.layouts import gridplot

from numpy import linspace, sinc, cos, pi

x = linspace(-2,2,5)
y = [1 if z <= 0.5 and z >= -0.5 else 0 for z in x]
p1 = figure(title = "Time Domain")
p1.step(x, y, line_width=2, mode="center")

x = linspace(-20,20,400)  
y = sinc(x)
p2 = figure(title = "Frequence Domain")
p2.line(x, y, line_width=2)

x = linspace(-2,2,200)
y = cos(10*pi*x)
p3 = figure(title = "Time Domain")
p3.line(x,y, line_width=2)

x = [-5,5]
y = [.5, .5]
p4 = figure(title = "Frequence Domain")
p4.triangle(x, y, size=20)
p4.segment(x0 = x, y0 = y, x1 = x, y1 = [0,0], line_width=2)

x = linspace(-2,2,200)
y = [cos(10*pi*z) if z <= 0.5 and z >= -0.5 else 0 for z in x]
p5 = figure(title = "Time Domain")
p5.line(x, y, line_width=2)

x = linspace(-20,20,400)
y = sinc(x-5) + sinc(x+5)
p6 = figure(title = "Frequency Domain")
p6.line(x, y/2, line_width=2)

p = gridplot([p1, p3, p5, p2, p4, p6], ncols = 3, plot_width = 400, plot_height = 300)

js, tag = autoload_static(p, CDN, filename)
f = open(filename, "w")
f.write(js)
f.close()

print(tag)
#+END_SRC

#+RESULTS:
#+begin_export html

<script src="figures/modulation.js" id="835a8023-02d2-4835-a104-f9f0115ecd25"></script>
#+end_export

** Amplitude-Shift Keying

** Frequency-Shift Keying
   

** Phase-Shift Keying
   
*** Constellation Graph
    
** QAM
 
* Free Space Propagation Model
  
** Free Space Loss
  
*** Impairments
- *Free space loss*
- *Noise*
- Fading 
  - Multi-path (Next Section)
- Atmospheric absorption

*** Friis Transmission Equation
 
** Noise
- Thermal Noise(John-Nyquist Noise)
  - Noise seen in switching circuits due to electrons
- Inter-modulation noise
  - Noise caused by signals at different frequencies on the same medium
- Crosstalk
  - coupling between signal paths
- Impulse Noise
  - Power spike (e.g. from thunder)

*** Thermal Noise


- White noise since it contains the same level of power at all frequencies
 \[N = ktB\]
- \(k\) is the Boltzmann’s constant: \(1.381\times 10^{-21} W/(K\cdot Hz)\),
- \(T\) is the absolute temperature in Kelvin, and
- \(B\) is the bandwidth.
- At room temperature, \(T = 290K\), the thermal noise power spectral density
  \(kT =  –174 dBm/Hz\)

** Shannon Channel Capacity Theorem

* Multi-Path Problem 
 
** Multi-path
   
*** Impairments
- Free space loss
- Noise
- Fading 
  - *Multi-path*
- Atmospheric absorption

*** Multi-path
- Multi-path: obstacles reflect signals so that multiple copies with varying delays are received
  - Reflection - occurs when signal encounters a surface that is large relative to the wavelength of the signal
  - Diffraction - occurs at the edge of an impenetrable body that is large compared to wavelength of radio wave
  - Scattering – occurs when incoming signal hits an object whose size in the order of the wavelength of the signal or less

*** Reflection/Diffraction/Scattering

*** Reflecting Wall Example

*** Coherent Bandwidth

*** Intersymbol Interference
    
*** Mobile Object
    
*** Coherent Time


* Diversity
  
** Time Diversity 
   
** Frequency Diversity   
   
** Frequency Hopping Spread Spectrum
   
** OFDM
   
** Chirp Spread Spectrum 
   
** CDMA
   
* Physical Layer Protocol
** Bluetooth LE
   
** IEEE 802.15.4
   
** IEEE 802.11

** Cellular System
   
** LoRa
  
* Conclusion
